### ISSUE TITLE
During call, How to change the audio from loudspeaker to phone speaker vice versa

### ISSUE THREAD

**Issue by kmamtora** [livekit/client-sdk-react-native#54]
Hi Team,

I want an option to convert audio calls from loudspeakers to phone speakers and vice versa.

 await AudioSession.configureAudio({
          android: {
            preferredOutputList: ['speaker'],
          },
          ios: {
            defaultOutput: 'speaker',
          },
        });

I know this is for loudspeaker but how do I convert to phone

**Comment by davidliu** [comment]
See https://htmlpreview.github.io/?https://raw.githubusercontent.com/livekit/client-sdk-react-native/main/docs/classes/AudioSession.html#selectAudioOutput

**Comment by awlui** [comment]
Hey all, I'm running into this same issue. If we configure `"speaker"` as the `"defaultOutput"`, then we are given no option to select the phone receiver. What the `"default"` value that we provide to `selectAudioOutput` becomes is either the phone's speaker or headset, if it is connected.

Selecting the phone receiver is only possible if we provide `"earpiece"` as the `"defaultOutput"`. Then `"default"` is either the receiver or headset. From there we can toggle to speaker with the `"force_speaker"` option.


But, my desired behavior is to have speaker be the default, but for receiver to be an option(`"default"`) that we can select with `selectAudioOutput`. I attempted a workaround by setting `"earpiece"` as the `"defaultOutput"` but then immediately calling `selectAudioOutput` with `"forceSpeaker"`. The issue is that the underlying call to `overrideOutputAudioPort` returns an error and fails to perform the update. There seems to be some period after `configureAudio` where you can't call `selectAudioOutput` because it'll fail. If I wait like 3-5 seconds, that `selectAudioOutput` call works.


*also a side question:
I noticed that the `startAudioSession` implementation is empty. I would've expected maybe `setActive` to be called here. But I don't see it called anywhere. How does this work?

**Comment by lifeoasis-chudee** [comment]
@awlui 
I don't know if this will help, but I set the initial audio settings to 
I forced it to switch to speaker mode when the LocalTrackPublished event is fired, as shown in the attached image. 

```
await AudioSession.configureAudio({
  android: {
    preferredOutputList: ["earpiece"],
  },
  ios: {
    defaultOutput: "earpiece",
  },
});
```

<img width="657" alt="image" src="https://github.com/livekit/client-sdk-react-native/assets/70566145/6ad9d7ca-bfac-4fcc-829a-3a4a51ee47df">
